language: rust
cache: cargo
git:
  submodules: false
matrix:
  allow_failures:
    - os: windows
    - rust: nightly
  fast_finish: true
os:
  - linux
  - osx
  - windows
rust:
  - stable
  - beta
  - nightly
script:
  - ./scripts/test.sh
